# Contoh atlas-credentials-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: atlas-credentials
type: Opaque
data:
  username: YWttYWw= # echo -n 'akmal' | base64
  password: YWttYWw= # echo -n 'password_atlas_mu' | base64