# k3s/deployments/backend-deployments.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: coelee/smarthome-backend:v1.1 # Pastikan image dan tag ini benar
          imagePullPolicy: Always 
          ports:
            - containerPort: 5000
          env:
            # Variabel untuk menampung kredensial Atlas dari Secret
            - name: ATLAS_USER 
              valueFrom:
                secretKeyRef:
                  name: atlas-credentials # Nama Secret untuk Atlas
                  key: username
            - name: ATLAS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atlas-credentials # Nama Secret untuk Atlas
                  key: password
            # MONGO_URI menggunakan variabel ATLAS_USER dan ATLAS_PASSWORD
            - name: MONGO_URI 
              value: "mongodb+srv://$(ATLAS_USER):$(ATLAS_PASSWORD)@iot.7l2nbtx.mongodb.net/smart_home?retryWrites=true&w=majority"
            # Variabel MONGO_INITDB_ROOT_USERNAME dan PASSWORD tidak lagi diperlukan di sini
            # karena kita tidak menginisialisasi MongoDB lokal di klaster.

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret # Pastikan secret ini ada dan berisi jwt-secret-key
                  key: jwt-secret-key
            - name: MQTT_BROKER_HOST
              value: "mqtt" # Nama Service MQTT di dalam klaster Kubernetes
            - name: MQTT_BROKER_PORT
              value: "1883" # Port TCP internal MQTT Service
            - name: MQTT_TOPIC_DEVICE_CONTROL_BASE
              value: "/home/device" 
            - name: MQTT_TOPIC_STATUS_BASE
              value: "/home/device" 
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000 
  type: LoadBalancer
