apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  jwt_secret: "LKJASPoipojadsfp21" # Ganti dengan base64 encoded dari secret key kamu
  # Untuk base64 encode: echo -n 'kunci_rahasia_jwt_kamu_yang_kuat' | base64